### ISSUE TITLE
it used to work but it dosent anymore

### ISSUE THREAD

**Issue by Gurenduben** [dreamscached/vanitygen-colab#1]
it now says 
(Reading database ... 155246 files and directories currently installed.)
Preparing to unpack libc6-udeb_2.24-11+deb9u4_amd64.udeb ...
Unpacking libc6-udeb (2.24-11+deb9u4) over (2.24-11+deb9u4) ...
Setting up libc6-udeb (2.24-11+deb9u4) ...
(Reading database ... 155246 files and directories currently installed.)
Preparing to unpack libcrypto1.0.2-udeb_1.0.2u-1~deb9u1_amd64.udeb ...
Unpacking libcrypto1.0.2-udeb (1.0.2u-1~deb9u1) over (1.0.2u-1~deb9u1) ...
Setting up libcrypto1.0.2-udeb (1.0.2u-1~deb9u1) ...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by dreamscached** [comment]
Unfortunately it seems that [exploitagency/vanitygen-plus](https://github.com/exploitagency/vanitygen-plus) is now gone, and because of that there's no way to retrieve its release package which was used in this notebook.

I'll look into it and try to see if there's anything I can do, and if it's recoverable I'll update the notebook and close this issue.

Thanks for reporting!

**Comment by dreamscached** [comment]
For now it seems that it's sufficient to use link from the web archive. Notebook works as it did before.

**Comment by Gurenduben** [comment]
But it doesn't

**Comment by Gurenduben** [comment]
You can use my fork of vanitygen PLUS for the colab notebook
